### PR TITLE
Address some windows build issues

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@johnwason I ported your changes here based on the latest but tesseract_motion_planners is failing but I do not see anything in the log indicating what the issue is. Do you see anything?

**Comment by johnwason** [comment]
This is the error I see:

```
[41/61] Building CXX object trajopt\CMakeFiles\tesseract_motion_planners_trajopt.dir\src\profile\trajopt_default_composite_profile.cpp.obj      
FAILED: trajopt/CMakeFiles/tesseract_motion_planners_trajopt.dir/src/profile/trajopt_default_composite_profile.cpp.obj
C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_CHRONO_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_CONTAINER_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK=1 -DBOOST_FILESYSTEM_NO_LIB -DBOOST_GRAPH_DYN_LINK -DBOOST_GRAPH_NO_LIB -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_IOSTREAMS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_RANDOM_DYN_LINK -DBOOST_RANDOM_NO_LIB -DBOOST_SERIALIZATION_DYN_LINK -DBOOST_SERIALIZATION_NO_LIB -DBOOST_STACKTRACE_DYN_LINK -DBOOST_STACKTRACE_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DBOOST_THREAD_USE_DLL -DBT_USE_DOUBLE_PRECISION -DBoost_USE_MULTITHREADED=ON -DBoost_USE_STATIC_LIBS=OFF -DBoost_USE_STATIC_RUNTIME=OFF -DEIGEN_HAS_CXX17_OVERALIGN=0 -DTESSERACT_ASSIMP_USE_PBRMATERIAL=1 -DTESSERACT_PARSE_POINT_CLOUDS=\"ON\" -DTINYXML2_IMPORT -DTRAJOPT_DATA_DIR=\"C:/ws/tesseract_dev/tesseract_ws/install/share/trajopt_common/data\" -D_FILE_OFFSET_BITS=64 -D_USE_MATH_DEFINES=ON -D__SSE2__ -D__SSE3__ -D__SSE4_1__ -D__SSE4_2__ -D__SSE__ -D__SSSE3__ -Dtesseract_motion_planners_trajopt_EXPORTS -IC:\ws\tesseract_dev\tesseract_ws\src\tesseract_planning\tesseract_motion_planners\trajopt\include -IC:\ws\tesseract_dev\tesseract_ws\src\tesseract_planning\tesseract_motion_planners\core\include 
-IC:\ws\tesseract_dev\tesseract_ws\src\tesseract_planning\tesseract_motion_planners\simple\include -external:IC:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\eigen3 -external:IC:\ws\tesseract_dev\tesseract_ws\install\include -external:IC:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include -external:IC:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\bullet -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /MD /O0 /Ob0 /Zi /DNDEBUG /bigobj -std:c++17 -MD -openmp /showIncludes /Fotrajopt\CMakeFiles\tesseract_motion_planners_trajopt.dir\src\profile\trajopt_default_composite_profile.cpp.obj /Fdtrajopt\CMakeFiles\tesseract_motion_planners_trajopt.dir\ /FS -c C:\ws\tesseract_dev\tesseract_ws\src\tesseract_planning\tesseract_motion_planners\trajopt\src\profile\trajopt_default_composite_profile.cpp
cl : Command line warning D9002 : ignoring unknown option '/O0'
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/serialization/access.hpp(116): error C2039: 'serialize': is not a member of 'trajopt_common::SafetyMarginData'
C:\ws\tesseract_dev\tesseract_ws\install\include\trajopt_common/fwd.h(6): note: see declaration of 'trajopt_common::SafetyMarginData'
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/serialization/serialization.hpp(59): note: see reference to function 
template instantiation 'void boost::serialization::access::serialize<Archive,T>(Archive &,T &,const unsigned int)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/serialization/serialization.hpp(109): note: see reference to function template instantiation 'void boost::serialization::serialize<Archive,T>(Archive &,T &,const unsigned int)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(159): note: see reference to function 
template instantiation 'void boost::serialization::serialize_adl<Archive,T>(Archive &,T &,const unsigned int)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(151): note: while compiling class template member function 'void boost::archive::detail::oserializer<Archive,T>::save_object_data(boost::archive::detail::basic_oarchive &,const void 
*) const'
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(176): note: see reference to class template instantiation 'boost::archive::detail::oserializer<Archive,T>' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(173): note: while compiling class template member function 'const boost::archive::detail::basic_oserializer &boost::archive::detail::pointer_oserializer<Archive,T>::get_basic_serializer(void) const'
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(372): note: see reference to class template instantiation 'boost::archive::detail::pointer_oserializer<Archive,T>' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(469): note: see reference to function 
template instantiation 'void boost::archive::detail::save_pointer_type<Archive>::non_polymorphic::save<T>(Archive &,T &)' being compiled        
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(469): note: see reference to function 
template instantiation 'void boost::archive::detail::save_pointer_type<Archive>::non_polymorphic::save<T>(Archive &,T &)' being compiled        
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(482): note: see reference to function 
template instantiation 'void boost::archive::detail::save_pointer_type<Archive>::save<T>(Archive &,const T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(482): note: see reference to function 
template instantiation 'void boost::archive::detail::save_pointer_type<Archive>::save<T>(Archive &,const T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(541): note: see reference to function 
template instantiation 'void boost::archive::detail::save_pointer_type<Archive>::invoke<const T>(Archive &,const TPtr)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=const trajopt_common::SafetyMarginData *,
            TPtr=const trajopt_common::SafetyMarginData *
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(541): note: see reference to function 
template instantiation 'void boost::archive::detail::save_pointer_type<Archive>::invoke<const T>(Archive &,const TPtr)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=const trajopt_common::SafetyMarginData *,
            TPtr=const trajopt_common::SafetyMarginData *
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/common_oarchive.hpp(71): note: see reference to function template instantiation 'void boost::archive::save<Archive,T>(Archive &,T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=const trajopt_common::SafetyMarginData *
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/basic_xml_oarchive.hpp(100): note: see reference to function 
template instantiation 'void boost::archive::detail::common_oarchive<Archive>::save_override<const T>(T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=const trajopt_common::SafetyMarginData *
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/basic_xml_oarchive.hpp(100): note: see reference to function 
template instantiation 'void boost::archive::detail::common_oarchive<Archive>::save_override<const T>(T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=const trajopt_common::SafetyMarginData *
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/interface_oarchive.hpp(71): note: see reference to function template instantiation 'void boost::archive::basic_xml_oarchive<Archive>::save_override<const T*>(const boost::serialization::nvp<const T 
*> &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/interface_oarchive.hpp(71): note: see reference to function template instantiation 'void boost::archive::basic_xml_oarchive<Archive>::save_override<const T*>(const boost::serialization::nvp<const T 
*> &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/serialization/shared_ptr.hpp(236): note: see reference to function template instantiation 'Archive &boost::archive::detail::interface_oarchive<Archive>::operator <<<boost::serialization::nvp<const T *>>(const boost::serialization::nvp<const T *> &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/serialization/shared_ptr.hpp(236): note: see reference to function template instantiation 'Archive &boost::archive::detail::interface_oarchive<Archive>::operator <<<boost::serialization::nvp<const T *>>(const boost::serialization::nvp<const T *> &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=trajopt_common::SafetyMarginData
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/serialization/split_free.hpp(44): note: see reference to function template instantiation 'void boost::serialization::save<Archive,trajopt_common::SafetyMarginData>(Archive &,const std::shared_ptr<trajopt_common::SafetyMarginData> &,const unsigned int)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/serialization/split_free.hpp(40): note: while compiling class template member function 'void boost::serialization::free_saver<Archive,T>::invoke(Archive &,const T &,const unsigned int)'
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/serialization/split_free.hpp(72): note: see reference to function template instantiation 'void boost::serialization::free_saver<Archive,T>::invoke(Archive &,const T &,const unsigned int)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/serialization/split_free.hpp(72): note: see reference to class template instantiation 'boost::serialization::free_saver<Archive,T>' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/serialization/shared_ptr.hpp(273): note: see reference to function template instantiation 'void boost::serialization::split_free<Archive,std::shared_ptr<trajopt_common::SafetyMarginData>>(Archive &,T &,const unsigned int)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/serialization/serialization.hpp(109): note: see reference to function template instantiation 'void boost::serialization::serialize<Archive,trajopt_common::SafetyMarginData>(Archive &,std::shared_ptr<trajopt_common::SafetyMarginData> &,const unsigned int)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(159): note: see reference to function 
template instantiation 'void boost::serialization::serialize_adl<Archive,T>(Archive &,T &,const unsigned int)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(151): note: while compiling class template member function 'void boost::archive::detail::oserializer<Archive,T>::save_object_data(boost::archive::detail::basic_oarchive &,const void 
*) const'
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(265): note: see reference to class template instantiation 'boost::archive::detail::oserializer<Archive,T>' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(317): note: see reference to function 
template instantiation 'void boost::archive::detail::save_non_pointer_type<Archive>::save_standard::invoke<T>(Archive &,const T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(317): note: see reference to function 
template instantiation 'void boost::archive::detail::save_non_pointer_type<Archive>::save_standard::invoke<T>(Archive &,const T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(541): note: see reference to function 
template instantiation 'void boost::archive::detail::save_non_pointer_type<Archive>::invoke<const T>(Archive &,const T &)' being compiled       
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/oserializer.hpp(541): note: see reference to function 
template instantiation 'void boost::archive::detail::save_non_pointer_type<Archive>::invoke<const T>(Archive &,const T &)' being compiled       
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/common_oarchive.hpp(71): note: see reference to function template instantiation 'void boost::archive::save<Archive,T>(Archive &,T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/basic_xml_oarchive.hpp(100): note: see reference to function 
template instantiation 'void boost::archive::detail::common_oarchive<Archive>::save_override<const T>(T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/basic_xml_oarchive.hpp(100): note: see reference to function 
template instantiation 'void boost::archive::detail::common_oarchive<Archive>::save_override<const T>(T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=std::shared_ptr<trajopt_common::SafetyMarginData>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/interface_oarchive.hpp(71): note: see reference to function template instantiation 'void boost::archive::basic_xml_oarchive<Archive>::save_override<std::shared_ptr<trajopt_common::SafetyMarginData>>(const boost::serialization::nvp<std::shared_ptr<trajopt_common::SafetyMarginData>> &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/interface_oarchive.hpp(71): note: see reference to function template instantiation 'void boost::archive::basic_xml_oarchive<Archive>::save_override<std::shared_ptr<trajopt_common::SafetyMarginData>>(const boost::serialization::nvp<std::shared_ptr<trajopt_common::SafetyMarginData>> &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/interface_oarchive.hpp(78): note: see reference to function template instantiation 'Archive &boost::archive::detail::interface_oarchive<Archive>::operator <<<T>(const T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=boost::serialization::nvp<std::shared_ptr<trajopt_common::SafetyMarginData>>
        ]
C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/archive/detail/interface_oarchive.hpp(78): note: see reference to function template instantiation 'Archive &boost::archive::detail::interface_oarchive<Archive>::operator <<<T>(const T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=boost::serialization::nvp<std::shared_ptr<trajopt_common::SafetyMarginData>>
        ]
C:\ws\tesseract_dev\tesseract_ws\src\tesseract_planning\tesseract_motion_planners\trajopt\src\profile\trajopt_default_composite_profile.cpp(487): note: see reference to function template instantiation 'Archive &boost::archive::detail::interface_oarchive<Archive>::operator &<boost::serialization::nvp<std::shared_ptr<trajopt_common::SafetyMarginData>>>(const T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=boost::serialization::nvp<std::shared_ptr<trajopt_common::SafetyMarginData>>
        ]
C:\ws\tesseract_dev\tesseract_ws\src\tesseract_planning\tesseract_motion_planners\trajopt\src\profile\trajopt_default_composite_profile.cpp(487): note: see reference to function template instantiation 'Archive &boost::archive::detail::interface_oarchive<Archive>::operator &<boost::serialization::nvp<std::shared_ptr<trajopt_common::SafetyMarginData>>>(const T &)' being compiled
        with
        [
            Archive=boost::archive::xml_oarchive,
            T=boost::serialization::nvp<std::shared_ptr<trajopt_common::SafetyMarginData>>
        ]
C:\ws\tesseract_dev\tesseract_ws\src\tesseract_planning\tesseract_motion_planners\trajopt\src\profile\trajopt_default_composite_profile.cpp(494): note: see reference to function template instantiation 'void tesseract_planning::TrajOptDefaultCompositeProfile::serialize<boost::archive::xml_oarchive>(boost::archive::xml_oarchive &,const unsigned int)' being compiled
```

**Comment by Levi-Armstrong** [comment]
Is there a reason this does not show up in CI logs?

**Comment by johnwason** [comment]
I am using `--event-handlers console_cohesion+`. I don't see that argument being passed to colcon.

**Comment by johnwason** [comment]
Huh ok that built and now we are just seeing the `TesseractTaskComposerFactoryUnit.LoadAndExportPluginTest (Failed)` error which is expected since trajopt_ifopt isn't being built.

**Comment by johnwason** [comment]
I had to pull `trajopt`. The build finished after I updated.

**Pull request merged**
