### PR TITLE
Fix windows CI by pinning cmake version to 3.28.x

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@johnwason Do you know how to resolve the windows build error ` unresolved external symbol _Thrd_sleep_for`.

**Comment by johnwason** [comment]
I will take a look

**Comment by johnwason** [comment]
@Levi-Armstrong you need to use the cmake fix for Mac OS as well since that uses vcpkg, and apparently it is in compatible with the latest cmake version.

**Comment by johnwason** [comment]
I found a syntax error report:

```
 D:\a\tesseract_planning\tesseract_planning\upstream_ws\install\tesseract_common\include\tesseract_common/kinematic_limits.h(147): error C2059: syntax error: '('
```

**Comment by Levi-Armstrong** [comment]
@johnwason I fixed the kinematics error, but do you know how to solve the current issue?

**Comment by johnwason** [comment]
I guess this was fixed by cmake. Closing

**Pull request closed without merging**
