### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by marip8**
This PR updates the CI jobs to correspond to [this Tesseract PR](https://github.com/tesseract-robotics/tesseract/pull/861) that introduces ROS-independent CI

### CODE REVIEW

**Comment by marip8** [comment]
> Not sure what is wrong with the ubuntu builds, but I do see this message.
> 
> ```
> Could not extract environment variable 'ROS_DISTRO' from the docker image 'ghcr.io/tesseract-robotics/tesseract:focal-0.15'; proceeding without 'ROS_DISTRO'
> ```

I added this as a change to industrial_ci. It should be fine. I think the problem was that I made a script to add the ROS-I PPA and forgot to use the -y option for auto confirmation

**Comment by Levi-Armstrong** [comment]
@marip8 I think you need to rebase and the checks should run.

**Comment by Levi-Armstrong** [comment]
@marip8 Any update on this? It is a pain pulling down MR's, building them locally and running the tests.

**Comment by Levi-Armstrong** [comment]
I have pushed but taskflow 0.3..5 focal and bionic to the ROS-I PPA which should be available soon.

**Pull request merged**
