### PR TITLE
Add serialization for ProcessPlanningRequest

### PR DESCRIPTION
**Pull request by mpowelson**
This depends on https://github.com/tesseract-robotics/tesseract/pull/726

### CODE REVIEW

**Review by Levi-Armstrong — APPROVED** [review]
I noticed that a few item were not being serialized which you documented. Is the plan to merge as is or is this still in work?

**Comment by mpowelson** [comment]
> I noticed that a few item were not being serialized which you documented. Is the plan to merge as is or is this still in work?

I'm going to integrate it into our system today. I anything pops up during that process, I will change it. Otherwise, I was thinking this would be ok for now, and we can make follow on improvements as we use it.

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by Levi-Armstrong** [comment]
@mpowelson I just created a PR against Tesseract adding atomic serialization support.

**Comment by mpowelson** [comment]
I pushed the serialization for abort_. It now depends on https://github.com/tesseract-robotics/tesseract/runs/5681420604?check_suite_focus=true

**Comment by Levi-Armstrong** [comment]
I just merged the tesseract PR and created a release so should have a new docker soon and be able to restart it.

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by Levi-Armstrong** [comment]
@mpowelson It looks like clang-tidy is not happy due to this [error](bugprone-unhandled-self-assignment).

**Review by Levi-Armstrong — APPROVED** [review]

**Pull request merged**
