### PR TITLE
Refactor using MoveInstructionPoly

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
Benchmark results did not change
``` bash
-----------------------------------------------------------------------------
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
BM_InstructionPolyCreation               29.3 ns         29.3 ns     23934246
BM_WaypointPolyCreation                  7.90 ns         7.90 ns     85827226
BM_CompositeInstructionCreation          80.1 ns         80.1 ns      8641292
BM_ProgramCreation                      32433 ns        32432 ns        21515
BM_InstructionPolyCopy                   69.9 ns         69.9 ns      9678933
BM_WaypointPolyCopy                      18.8 ns         18.8 ns     36863981
BM_CompositeInstructionCopy              5528 ns         5527 ns       125682
BM_InstructionPolyAssign                 70.5 ns         70.5 ns      9846056
BM_WaypointPolyAssign                    18.9 ns         18.9 ns     36878106
BM_CompositeInstructionAssign            5680 ns         5680 ns       126607
BM_InstructionPolyCast                   2.01 ns         2.01 ns    355746067
BM_WaypointPolyCast                      1.97 ns         1.97 ns    354696558
BM_InstructionPolyAccess                 2.19 ns         2.19 ns    319959269
BM_WaypointPolyAccess                   0.328 ns        0.328 ns   1000000000
BM_VectorStateWaypointPolyCreation     136900 ns       136900 ns         5116
BM_VectorStateWaypointUPtrCreation     140351 ns       140350 ns         4939
BM_VectorStateWaypointPolyCopy          85081 ns        85080 ns         8176
BM_VectorStateWaypointUPtrCopy          85874 ns        85869 ns         8024
```

**Comment by Levi-Armstrong** [comment]
The increase in composite copy and assign was because of making move instruction virtual. Removing these the results are back down.
``` bash
-----------------------------------------------------------------------------
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
BM_InstructionPolyCreation              0.000 ns        0.000 ns   1000000000
BM_WaypointPolyCreation                 0.000 ns        0.000 ns   1000000000
BM_CompositeInstructionCreation          62.4 ns         62.4 ns     12406001
BM_ProgramCreation                      30203 ns        30204 ns        23086
BM_InstructionPolyCopy                   63.7 ns         63.7 ns      9585454
BM_WaypointPolyCopy                      19.3 ns         19.3 ns     36500879
BM_CompositeInstructionCopy              5596 ns         5596 ns       120838
BM_InstructionPolyAssign                 61.5 ns         61.5 ns     11257761
BM_WaypointPolyAssign                    19.2 ns         19.2 ns     36165707
BM_CompositeInstructionAssign            5637 ns         5637 ns       118650
BM_InstructionPolyCast                   1.97 ns         1.97 ns    356162498
BM_WaypointPolyCast                      1.75 ns         1.75 ns    400456039
BM_InstructionPolyAccess                 2.18 ns         2.18 ns    320344129
BM_WaypointPolyAccess                   0.218 ns        0.218 ns   1000000000
BM_VectorStateWaypointPolyCreation     146107 ns       146106 ns         4828
BM_VectorStateWaypointUPtrCreation     136788 ns       136789 ns         5118
BM_VectorStateWaypointPolyCopy          83602 ns        83603 ns         8392
BM_VectorStateWaypointUPtrCopy          83311 ns        83311 ns         8243
```

**Comment by johnwason** [comment]
Please hold off creating a new version until I make sure there aren't any patches needed for swig.

**Comment by Levi-Armstrong** [comment]
Sure thing. I plan to wait till I get the motion planners refactored to create a release.

**Pull request merged**
