### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@johnwason Can you test this branch?

**Comment by johnwason** [comment]
I fixed a few errors but am still getting `C:\ws\tesseract_dev\vcpkg\installed\x64-windows-v142-release\include\boost/serialization/access.hpp(116): error C2039: 'serialize': is not a member of 'trajopt_common::SafetyMarginData'`

**Comment by Levi-Armstrong** [comment]
It looks like it getting past the build stage now.

**Comment by johnwason** [comment]
Oh I left comments on the other PR. Yes the test that is failing is expected. It is the `TesseractTaskComposerFactoryUnit.LoadAndExportPluginTest (Failed)` error which is expected since trajopt_ifopt isn't being built.

**Comment by Levi-Armstrong** [comment]
@johnwason Thanks for the help.

**Pull request merged**
