### PR TITLE
Adding Trajopt_Ifopt option to all examples

### PR DESCRIPTION
**Pull request by rjoomen**
Examples
- [x] car_seat_example
- [x] freespace_hybrid_example
- [x] pick_and_place_example
- [x] puzzle_piece_auxillary_axes_example _(but "TrajOpt IFOPT currently does not support dynamic cartesian waypoints!")_
- [x] puzzle_piece_example

Other examples
- [x] basic_cartesian_example (already present)
- [x] glass_upright_example (already present)
- [x] online_planning_example (always Ifopt)
- [x] scene_graph_example (no planning involved)
- [x] freespace_ompl_example (OMPL only)
- [x] glass_upright_ompl_example (OMPL only)

Other
- [x] Add FreespaceIfoptPipeline and FreespaceIfoptTask to task_composer_plugins.yaml so the OMPL hybrid example can use Trajopt_Ifopt
- [x] Modify all tesseract_ros2 examples to be able to test this (https://github.com/tesseract-robotics/tesseract_ros2/pull/91)

### CODE REVIEW

**Comment by rjoomen** [comment]
@Levi-Armstrong I can't get the car_seat_example to place the seat using Ifopt. Could you take a look? Maybe my choice of parameters is wrong.

**Comment by Levi-Armstrong** [comment]
> @Levi-Armstrong I can't get the car_seat_example to place the seat using Ifopt. Could you take a look? Maybe my choice of parameters is wrong.

I will take a look, but I am not surprised that this was is not working with the Ifopt version based on our discussion about the collision implementation. I am working on moving the collision utilities to trajopt_common so we can update the legacy code to help compare the two.

**Comment by Levi-Armstrong** [comment]
I imagine some the issues my be resolved with the latest fixes in TrajOpt 0.7.2 release. Does this release fix any of the examples?

**Comment by rjoomen** [comment]
All applicable examples have an Ifopt option added now. I got the car_seat_example working, the puzzle_piece_example and pick_and_place_example do not converge, so I disabled their unit tests.

This is ready for review now.

**Comment by Levi-Armstrong** [comment]
@rjoomen I think you just need to update a unit test because you modified the task_composer_plugins.yaml.

**Comment by Levi-Armstrong** [comment]
@rjoomen It looks like another test is failing.
```
2024-01-17T19:43:15.0335977Z 5: [ RUN      ] TesseractExamples.GlassUprightTrajOptExampleUnit
2024-01-17T19:43:15.2321985Z 5: Info:    glass upright plan example
2024-01-17T19:43:15.2390217Z 5: Program: Composite Instruction, Description: Tesseract Composite Instruction
2024-01-17T19:43:15.2391605Z 5: Program: {
2024-01-17T19:43:15.2394743Z 5: Program:   Move Instruction, Move Type: 0, State WP: Pos=   -0.4  0.2762       0 -1.3348       0  1.4959       0
2024-01-17T19:43:15.2396646Z 5: , Description: Start Instruction
2024-01-17T19:43:15.2399950Z 5: Program:   Move Instruction, Move Type: 0, State WP: Pos=    0.4  0.2762       0 -1.3348       0  1.4959       0
2024-01-17T19:43:15.2401575Z 5: , Description: freespace_plan
2024-01-17T19:43:15.2402084Z 5: Program: }
2024-01-17T19:43:15.2882494Z 5: Info:    1 JointVelTermInfo coeffs given. Applying to all 7 joints
2024-01-17T19:43:15.2883310Z 5: Info:    1 JointVelTermInfo targets given. Applying to all 7 joints
2024-01-17T19:43:15.6667157Z 5: Info:    TrajOptMotionPlannerTask motion planning failed (Failed to find valid solution) for process input: Tesseract Composite Instruction
2024-01-17T19:43:15.6673985Z 5: Info:    Planning took 0.404566 seconds.
2024-01-17T19:43:15.6674984Z 5: Info:    Final trajectory is collision free
2024-01-17T19:43:15.6696994Z 5: /__w/tesseract_planning/tesseract_planning/target_ws/src/tesseract_examples/test/glass_upright_example_unit.cpp:25: Failure
2024-01-17T19:43:15.6698239Z 5: Value of: example.run()
2024-01-17T19:43:15.6698726Z 5:   Actual: false
2024-01-17T19:43:15.6699117Z 5: Expected: true
2024-01-17T19:43:15.6706477Z 5: [  FAILED  ] TesseractExamples.GlassUprightTrajOptExampleUnit (639 ms)
```

**Comment by rjoomen** [comment]
Yes, weird, because it does pass on stable. I'll look into it.

**Comment by Levi-Armstrong** [comment]
@marrts I think your changes to trajopt has broken a few examples because master unstable has two failing tests. Do you mind taking a look?

**Comment by marrts** [comment]
> @marrts I think your changes to trajopt has broken a few examples because master unstable has two failing tests. Do you mind taking a look?

Looking into it

**Comment by Levi-Armstrong** [comment]
I worked a fix this weekend and should have PR up this coming weekend.

**Comment by Levi-Armstrong** [comment]
I think with the bug fixes in trajopt you might be able to enable all of the examples!

**Comment by Levi-Armstrong** [comment]
@rjoomen Does the car seat work with Ifopt?

**Comment by Levi-Armstrong** [comment]
I will review this over the weekend.

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by Levi-Armstrong** [comment]
Please squash merge, after CI is passing.

**Comment by Levi-Armstrong** [comment]
It looks like the pick and place example for ifopt is failing.

**Comment by Levi-Armstrong** [comment]
@rjoomen I pushed a commit fixing the pick and place example. I just had to update the configuration to match the original trajopt and everything was able to plan. It is starting to look like the ifopt version now aligns with the legacy trajopt.

**Comment by rjoomen** [comment]
I am not allowed merge, as the _stable_ checks are marked as required and did not pass. (Is it correct they should be required?)

**Comment by Levi-Armstrong** [comment]
@rjoomen Thank you!

**Pull request merged**
