### PR TITLE
Reduce CI-built docker image size 

### PR DESCRIPTION
**Pull request by marip8**
Mirrors [`tesseract` PR 911](https://github.com/tesseract-robotics/tesseract/pull/911)

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
So it looks like removing all -dev apt components breaks the build because dependencies required by tesseract are still required to build these packages. @marip8 Any ideas on how best to resolve this?

**Comment by marip8** [comment]
> So it looks like removing all -dev apt components breaks the build because dependencies required by tesseract are still required to build these packages. @marip8 Any ideas on how best to resolve this

Addressed in [`tesseract` PR 913](https://github.com/tesseract-robotics/tesseract/pull/913)

**Comment by marip8** [comment]
I'll wait ~30 minutes for the new `tesseract` docker image to be pushed before I re-run CI here. I'll remove the deletion of the `-dev` libraries from this CI config as well

**Comment by marip8** [comment]
Looks like OMPL failed a unit test (seemingly randomly). @Levi-Armstrong any ideas why?

**Review by Levi-Armstrong — APPROVED** [review]

**Pull request merged**
